# netlify.toml - Configuration file for Netlify deployments

[build]
  # Directory to publish (the folder that contains the built site)
  publish = "dist"
  # Build command
  command = "npm run build"
  # Serverless functions directory
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["server-utils/**", "data/**"]
  
# Environment plugin removed; nothing to load here.

# API redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Redirects for SPA (Single Page Application) routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and caching
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' identity.netlify.com unpkg.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' *.netlify.app *.netlify.com identity.netlify.com api.netlify.com;"

# Relaxed CSP only for the CMS admin app
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' identity.netlify.com unpkg.com blob:; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' *.netlify.app *.netlify.com identity.netlify.com api.netlify.com; frame-src app.netlify.com; worker-src 'self' blob:;"

# Environment variables - NOTE: Set sensitive values in Netlify UI, not here!
[build.environment]
  NODE_VERSION = "18"
