backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "books"
    label: "Books"
    label_singular: "Book"
    folder: "data/books"
    create: true
    format: "json"
    extension: "json"
    slug: "{{slug}}"
    identifier_field: title
    sortable_fields: ["title", "author", "category"]
    summary: "{{title}} — {{author}} ({{category}})"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Google Drive Link", name: "driveUrl", widget: "string" }
      - { label: "Category", name: "category", widget: "string", required: false, hint: "Leave blank for auto-detect" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Cover URL (optional)", name: "cover", widget: "string", required: false, hint: "Direct image URL (https://...)" }

  - name: "books_master"
    label: "Books Master (single file)"
    files:
      - label: "NUCES + CMS Books"
        name: "nucesBooksLocal"
        file: "data/nucesBooks.local.json"
        editor:
          preview: false
        description: "Use CMS Items to add/remove books. Raw NUCES list is for reference only."
        fields:
          - label: "Raw NUCES Items (do not edit)"
            name: "raw"
            widget: "list"
            allow_add: false
            collapsed: true
            summary: "{{fields.volumeInfo.title}}"
            fields:
              - label: "Volume Info"
                name: "volumeInfo"
                widget: "object"
                fields:
                  - { label: "Title", name: "title", widget: "string" }
                  - label: "Image Links"
                    name: "imageLinks"
                    widget: "object"
                    fields:
                      - { label: "Thumbnail", name: "thumbnail", widget: "string", required: false }
                  - { label: "Description", name: "description", widget: "text", required: false }
                  - { label: "Categories", name: "categories", widget: "list", default: [] }
              - { label: "Download Link", name: "downloadLink", widget: "string" }
              - { label: "Solution Link", name: "solutionLink", widget: "string", required: false }
            hint: "For reference only; avoid editing."
          - label: "CMS Items"
            name: "cmsItems"
            widget: "list"
            summary: "{{title}} — {{author}} ({{category}})"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Author", name: "author", widget: "string", required: false }
              - { label: "Google Drive Link", name: "driveUrl", widget: "string" }
              - { label: "Category", name: "category", widget: "string", required: false, hint: "Leave blank for auto-detect" }
              - { label: "Description", name: "description", widget: "text", required: false }
              - { label: "Cover URL (optional)", name: "cover", widget: "string", required: false, hint: "Direct image URL (https://...)" }
